general {
    lock_cmd = zsh $HOME/.config/hypr/scripts/lock.zsh
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300                                # 5 minutes
    on-timeout = loginctl lock-session           # Tells hyprland to run lock_cmd
}

listener {
    timeout = 600                                # 10 minutes
    on-timeout = hyprctl dispatch dpms off       # Turn off monitor
    on-resume = hyprctl dispatch dpms on         # Turn on monitor
}
